#!/bin/bash

# Verifica se apenas 1 argumento foi passado
if [ "$#" -ne 1 ]; then
    zenity --error --title="Erro" --text="Selecione apenas uma imagem!"
    exit 1
fi

set_img="$(readlink -m "$1")"

# Verifica se o arquivo existe
if [ ! -f "$set_img" ]; then
    zenity --error --title="Erro" --text="O arquivo não foi encontrado!"
    exit 1
fi

# Verifica a extensão do arquivo (suporta apenas jpg, jpeg, png, webp)
ext=$(echo "$set_img" | awk -F. '{print tolower($NF)}')
case "$ext" in
    jpg|jpeg|png|webp)
        # Aplica como papel de parede
        gsettings set org.gnome.desktop.background picture-uri "file://$set_img"
        gsettings set org.gnome.desktop.background picture-uri-dark "file://$set_img"
        zenity --info --title="Sucesso" --text="Wallpaper atualizado com sucesso!"
        ;;
    *)
        zenity --error --title="Erro" --text="Formato não suportado! Use JPG, PNG ou WEBP."
        ;;
esac

